### ISSUE TITLE
When daysUntilClose: false, issues are closed an hour after adding 'stale' label

### ISSUE THREAD

**Issue by grrowl** [probot/stale#102]
Here's our `.github/stale.yml`:

```yml
daysUntilStale: 3
daysUntilClose: false
exemptLabels:
  - put-on-ice
  - work-in-progress
staleLabel: stale
markComment: false
closeComment: false
```

Here's what's happening:

![image](https://user-images.githubusercontent.com/907140/36654909-ac40567c-1b13-11e8-8a23-737b6f8d6277.png)

On our repo, it appears to add the correct label after `daysUntilStale` days (at `2018-02-25T22:40:20Z`, but an hour later (at `2018-02-25T23:40:20Z`) it closes PRs which have been previously labelled as stale.

Running `probot-stale@1.1.0`
