### ISSUE TITLE
Using key 'daysUntilClose' with value 'false' under key 'pulls' still closes pull requests

### ISSUE THREAD

**Issue by johlju** [probot/stale#129]
I'm only want PR's to be marked as staled, and never closed. But issues should be marked staled and then closed. 
So I thought this configuration would work. But it seems that PR's are still closed, see example in PR https://github.com/johlju/DebugApps/pull/11.

Should this configuration work? 

```yml
limitPerRun: 30

pulls:
  daysUntilStale: 1
  daysUntilClose: false
  exemptProjects: true
  exemptMilestones: true
  staleLabel: abandoned
  exemptLabels:
    - needs review
    - on hold
    - waiting for CLA pass

  markComment: >
    Labeling this pull request (PR) as abandoned since it has gone 14 days or more
    since the last update. An abandoned PR can be continued by another contributor.
    The abandoned label will be removed if work on this PR is taken up again.

issues:
  daysUntilStale: 1
  daysUntilClose: 2
  exemptProjects: true
  exemptMilestones: true
  staleLabel: needs more information
  exemptLabels:
    - bug
    - enhancement
    - tests
    - documentation
    - resource proposal
    - on hold
    - new module submission
    - module proposal

  markComment: >
    This issue has been automatically marked as needs more information because
    it has not had activity from the community in the last 30 days. It will be
    closed if no further activity occurs within 10 days. If the issue is labelled
    with any of the work labels (e.g bug, enhancement, documentation, or tests)
    then the issue will not auto-close.

  closeComment: >
    This issue has been automatically closed because it is has not had activity
    from the community in the last 40 days.

```
