### ISSUE TITLE
Add forceLabels config

### ISSUE THREAD

**Issue by PhrozenByte** [probot/stale#135]
Most of our Issues on GitHub are rather user questions than actual Issues (forcing users to ask questions somewhere else doesn't work anyway, so…). We're using Stale bot (great work btw :+1:) to automatically close these Issues after some days with no activity. The `exemptLabels` config (together with `only: issues`) is great to exclude actual bug reports, feature requests etc. from this automatism. However, after solving these Issues, we would like to keep the Issues open for some days to encourage people to actually give feedback - immediately closing a Issues always has some smack of "fixed, go away, no feedback desired".

Thus I'd like to suggest something like a `forceLabels` config to overrule `exemptLabels`. Think of the following config:

```yml
exemptLabels:
  - bug
forceLabels:
  - solved
```

- A Issues with no labels is marked as stale after 60 days and closed after 7 more days with no activity.
- A Issue labelled with just `bug` is never marked as stale an thus never automatically closed.
- A Issue labelled with both `bug` and `solved` is marked as stale after 60 days and closed after 7 more days with no activity, i.e. `forceLabels: [ solved ]` overrules `exemptLabels: [ bug ]`.

**#edit:**
This is related to #37, even though I think (not 100% sure though) that the implementation there completely ignores `exemptLabels` if `onlyLabels` is present (what I'd assume by the name of `onlyLabels` and by calling it "whitelist") - whereas my suggested `forceLabels` and `exemptLabels` can (and must) co-exist. However, if one just configures `forceLabels` and sets `exemptLabels` to `[]`, `forceLabels` might implicitly act like a whitelist (kill two birds with one stone :smile:).

**Comment by johlju** [comment]
Sounds like there is a need for cases. First case that is true top-to-bottom will execute.

Quick example.

```yml
when:
  issues:
    onLabels:
      - solved
    exemptLabels:
      - on hold
    daysUntilStale: false
    daysUntilClose: 7
    exemptProjects: false
    exemptMilestones: false

    closeComment: >
      This issue has been automatically closed.

when:
    exemptLabels:
      - on hold
    daysUntilStale: 30
    daysUntilClose: 40
    exemptProjects: true
    exemptMilestones: true
    staleLabel: stale
    markComment: >
      This issue has been automatically marked as stale.

    closeComment: >
      This issue has been automatically closed.
```
