### ISSUE TITLE
Allow this to only apply to PRs

### ISSUE THREAD

**Issue by Hixie** [probot/stale#137]
With Flutter, we're definitely not interested in closing issues, since we are aware that we have thousands of issues and we do intend in due course to deal with them as our team grows -- some of our most valuable issues are those that were filed long ago and are just not at the top of our current priority list.

However, we do want to deal with old PRs. It would be nice if stale-bot could be told to only close stale PRs and ignore issues entirely.

**Comment by johlju** [comment]
I'm not sure, but I think this might work? 

```
# Configuration for probot-stale - https://github.com/probot/stale

limitPerRun: 30
only: pulls

pulls:
  daysUntilStale: 20
  daysUntilClose: 30
  exemptProjects: false
  exemptMilestones: false
  staleLabel: stale

  markComment: >
    Labeling this pull request (PR) as stale. 

  closeComment: >
    This issue has been automatically closed.
```
