### ISSUE TITLE
Configuring Stale across multiple repositories?

### ISSUE THREAD

**Issue by laurenyu** [probot/stale#141]
Hello, I'm working on configuring Stale with a growing number of repositories. Is there a way to have each of them reference the same yaml file so that future changes don't need to be made in each of the repositories separately?

**Comment by hiimbex** [comment]
Yes! we use [probot-config](https://github.com/probot/probot-config). Within an organization you can have shared settings like so:

```yml
# repo: octocat/.github:.github/stale.yml
shared1: will be merged
shared2: will also be merged

# repo: octocat/repo1:.github/stale.yml
_extends: .github
other: AAA

# repo: octocat/repo2:.github/stale.yml
_extends: .github
shared2: overrides shared2
other: BBB

# repo: octocat/repo3:.github/stale.yml
other: CCC # standalone, does not extend other configs
```

or
```yml
# repo: octocat/.github:.github/stale.yml
shared1: will be merged
shared2: will also be merged

# repo: octocat/repo1
# has no file but still inherits settings only from repo named .github
```

We recommend using a repo named: `.github` for these org settings, as we're building more features to make inheritance from that specific repo easier.

Gonna close since there's no action to be taken here, but feel free to follow up here if you have further questions about how this works.
