### ISSUE TITLE
Stale bot not working 🤖🤯️

### ISSUE THREAD

**Issue by fvcproductions** [probot/stale#155]
I installed Stale bot onto this repo https://github.com/gdisf/teaching-materials with the config file in `.github/stale.yml` but nothing has been marked stale yet?

```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - Epic

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not been updated in the last 30 days. It will be closed if no further activity occurs within the next 7 days. Feel free to reach out on the #opensource channel in our Slack team or mention an admin for further help and resources if they are needed.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: > 
  This issue has been automatically closed due to max staleness. Thank you for your contributions to Girl Develop It and feel free to open another PR at any time. 💛
```

https://github.com/gdisf/teaching-materials/blob/master/.github/stale.yml
