### ISSUE TITLE
Not working in a private repository

### ISSUE THREAD

**Issue by Mohamed3on** [probot/stale#160]
Hi! so we installed stale in one of our repos at @HelloFresh, and added this config:
```
# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 21

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  I've marked this as stale because it has not had
 recent activity. I will close it if no further activity occurs. If you want to keep it, please post an update on its status/what's blocking it. Thank you!
# Comment to post when removing the stale label.
 unmarkComment: >
 This issue is no longer stale, thanks for the update!

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
# if the PR has a blocked label, it won't be closed (please add the blocker in the PR)
pulls:
  exemptLabels:
    - blocked

 # if you want to keep a specific issue, you can add this label
issues:
  exemptLabels:
     - in progress


# Comment to post when closing a stale Issue or Pull Request.
# closeComment: >
#   Your comment here.

# to limit to only `issues` or `pulls` use the following
# only: issues
```
but 24 hours later, it still hasn't done anything. Is there something wrong in the config?
