### ISSUE TITLE
Stale not closing issues when GitHub permissions are changed

### ISSUE THREAD

**Issue by christianbundy** [probot/stale#174]
I think I found an edge-case in the GitHub permissions where Stale will add the correct labels but doesn't actually close them. This only happens when GitHub permissions are changed from allowing Stale on specific repositories to allowing Stale on *all* repositories.

### Steps

1. [Install Stale](https://github.com/apps/stale/installations/new) to an organization
2. Only allow access to a single repository
3. Wait a week (not sure if this step is necessary)
4. Change the GitHub permissions to allow access to "all repositories"

### Expected

Stale should label and close issues on all repositories.

### Actual

Stale labels issues on all repositories but only closes them on the first repository that it was given access to.

## Workaround

1. Go to GitHub settings for organization
2. Uninstall Stale
3. Reinstall Stale

## Details

Our config on all repos:

```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

It's valid YAML, and the only change we made from the [default config](https://github.com/apps/stale) is that the label was changed from `wontfix` to `stale`. We have [385 stale issues](https://github.com/issues?utf8=%E2%9C%93&q=user:ssbc+is:open+label:stale+sort:updated-asc) that were marked stale 8 days ago (plus a few hours) but weren't being closed.

The only closed issues were the ones from [the original repo we added Stale to](https://github.com/ssbc/secure-scuttlebutt/issues?utf8=%E2%9C%93&q=label:stale), but even though the GitHub permissions were changed to cover *all* repos it looks like Stale was only attempting to close issues on that first repo.

Please let me know if you need any info from me, but please don't make any changes to our issues/PRs to test. :upside_down_face:
