### ISSUE TITLE
Stale bot not closing issues

### ISSUE THREAD

**Issue by deepwell** [probot/stale#199]
On April 10th, 2019 I setup stale bot to mark issues as stale, and then auto close them. It's been almost 2 weeks and there has been no change on the tickets (some which are 2 years old that I expected to be marked as stale). Can you take a look and let me know if something is not configured correctly? Thanks.

Issues: https://github.com/deepwell/issues-v2/issues

`.github/stale.yml` looks like this:
```yaml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 365
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - security
  - type: data integrity
# Limit to only issues or pulls
only: issues
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in the last year. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
```
