### ISSUE TITLE
onlyLabels not working

### ISSUE THREAD

**Issue by takose** [probot/stale#207]
Hi 👋 

I tried to introduce stale bot to comment stale issues which has specific label, but stale bot has marked all issues. Can you take a look and let me know if something is not configured correctly? 

Here is test repository.
https://github.com/takose/stalebot-test

stale.yml
```yml
# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 1

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels: []

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels:
  - TestLavbel

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

# Label to use when marking as stale
staleLabel: wontfix

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  Please check progress.
```

Thanks.

**Comment by Gustry** [comment]
Same for me. Stale bot just marked all issues of my repository with `stale` 5 minutes, while I got only 2 issues with the label `candidate for closing`.

Link to my stale.yml: https://github.com/3liz/QuickOSM/blob/master/.github/stale.yml#L12

```yaml
# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels:
  - "candidate for closing"
```

Unfortunately, if no solution is found, I will have to disable stalebot because I don't want it to close all my issues.

**Comment by kesselb** [comment]
Looks like labels are always wrapped in quotes. Mind to try `candidate for closing` without quotes? The yaml validator does not complain about missing quotes.

https://github.com/probot/stale/blob/e3c53ebf879cccaf856fba1602fdd67f878c3ee3/lib/stale.js#L73-L74

**Comment by Gustry** [comment]
No, it is still not working without quotes, look at this issue: https://github.com/3liz/QuickOSM/issues/167#issuecomment-500105003 It's tagged stale a few minutes ago.

I made the following change to stalebot https://github.com/3liz/QuickOSM/commit/32762e99759127978bcd8e2c77298890f511079b

Thanks

**Comment by skjnldsv** [comment]
Yep, probot is using js-yaml.
https://nodeca.github.io/js-yaml/

And quote or no quote does not make a difference in the parsing at all.
https://github.com/probot/probot-config/blob/master/lib/index.js#L24

**Comment by takose** [comment]
I sent PR to fix this 😜
https://github.com/probot/stale/pull/213

**Comment by antelle** [comment]
Hi! Just came across the same issue, the bot closed some issues by mistake. I see that the pull request is very straightforward, can this please be merged 🙏? Not good to have it in production.

**Comment by skjnldsv** [comment]
@antelle you better run your own stale bot, there is not much activity here :(
Fork it and merge the pending pr https://github.com/probot/stale/pull/213

I'm running it via docke-compose

```yml
version: '2'
services:
  stalebot:
    image: skjnldsv/stale:latest 
    restart: always
    ports:
      - 3000:3000
    environment:
      - APP_ID=12345
      - WEBHOOK_SECRET=123456789123456789123456789
      # - LOG_LEVEL=debug
      - PRIVATE_KEY_PATH=/app/private-key.pem
    volumes:
      - ./private-key.pem:/app/private-key.pem:ro

```
