### ISSUE TITLE
Custom deployed stalebot still closing issues even if user responds with a comment

### ISSUE THREAD

**Issue by jeffchew** [probot/stale#240]
I recently deployed a custom stalebot (on IBM Cloud) that points to one of our Github enterprise repositories. We were testing out to see if stalebot ignores an issue once a user responds but apparently it closes the issue anyway:

<img width="800" alt="Screen Shot 2019-09-09 at 8 59 08 AM" src="https://user-images.githubusercontent.com/1641214/64532874-57429780-d2e0-11e9-8fc2-962f33b5f589.png">

I have deployed stalebot as-is once I cloned it, minus including a private pem file. I'm setting the APP_ID, WEBHOOK_SECRET, GHE_HOST, and PRIVATE_KEY_PATH as environment variables within IBM Cloud.

stale.yml configuration:
```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 2
# Issues with these labels will never be considered stale
exemptLabels:
  - 'type: a11y ♿️'
  - 'bug 🐛'
  - 'Severity 1 🚨'
  - 'priority: high'
# Label to use when marking an issue as stale
staleLabel: inactive
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  We've marked this issue as stale because there hasn't been any activity for a couple of weeks.
  If there's no further activity on this issue in the next three days then we'll close it. You can
  keep the conversation going with just a short comment. Thanks for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  As there's been no activity since this issue was marked as stale, we are auto-closing it.

```
