### ISSUE TITLE
Use the `.github/config.yml` instead?

### ISSUE THREAD

**Issue by charlike** [probot/stale#60]
Hey! It's great, but is a bit inconsistent to the other  available bot apps. Most of them read config from `.github/config.yml`, but this reads from `.github/stale.yml`. Is this for reason or isn't updated?

It's not a big problem, but I like consistency and everything to be in one file.

**Comment by hiimbex** [comment]
Historically, all the probot apps had their own configurations files with names related to what they did. More recently, as more apps get created, it seems kind of crazy to have so many configuration files. That's why I created all the [behaviorbot](https://github.com/behaviorbot) apps to all use a `.github/config.yml` file.

I wouldn't be opposed to adding an optional `config.yml` to stale. (Obviously, we don't want to stop supporting use of a `stale.yml`) So we could check if either a `stale.yml` exists or a `config.yml` and make sure the `config.yml` contained:
```yml
stale:
  # Configuration for probot-stale - https://github.com/probot/stale

  # Number of days of inactivity before an Issue or Pull Request becomes stale
  daysUntilStale: 60
  # Number of days of inactivity before a stale Issue or Pull Request is closed
  daysUntilClose: 7
  # Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
  exemptLabels:
    - pinned
    - security
  # Label to use when marking as stale
  staleLabel: wontfix
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
  # Comment to post when removing the stale label. Set to `false` to disable
  unmarkComment: false
  # Comment to post when closing a stale Issue or Pull Request. Set to `false` to disable
  closeComment: false
  # Limit to only `issues` or `pulls`
  # only: issues
```
And essentially wrapping all the stale parameters in a `stale` object.
